language: C

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: UPDATE_REPOSITORY="true"
    - os: linux
      dist: trusty
      sudo: required
      env: UPDATE_REPOSITORY="add-apt-repository -y ppa:octave/stable"
    - os: osx
      env: BUILD_MATLAB=0
    - os: osx
      env: BUILD_MATLAB=1

before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        git clone --depth 1 https://github.com/hpdata/gdutil $HOME/gdutil;
        pip install -r $HOME/gdutil/requirements.txt;
        sudo $UPDATE_REPOSITORY;
        sudo apt-get update -q;
        sudo apt-get install -y octave bsdtar liboctave-dev mpich2 libmpich2-dev;
        python $HOME/gdutil/gd_get_pub.py "$ACCESSKEY_LINUX" | sudo bsdtar zxf - -C /usr/local --strip-components 2;
        sudo ln -s -f $(ls /usr/local/MATLAB/R*/bin/mex) /usr/local/bin;
      fi'
  # For Mac, install Octave and link g++-7 to g++-mp
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        git clone --depth 1 https://github.com/hpdata/gdutil $HOME/gdutil;
        pip install -r $HOME/gdutil/requirements.txt;
        python $HOME/gdutil/gd_get_pub.py "$ACCESSKEY_LINUX" -o /tmp/mex.tgz;
        sudo bsdtar zxf /tmp/mex.tgz -C /Applications --strip-components 1;
        sudo ln -s -f $(ls /Applications/MATLAB_R*/bin/mex) /usr/local/bin;
        rm -f /tmp/mex.tgz;
        brew tap homebrew/science;
        brew update;
        brew install --without-java octave;
        brew install mpich2;
        ln -s -f /usr/local/bin/gcc-7 /usr/local/bin/gcc-mp;
        ln -s -f /usr/local/bin/g++-7 /usr/local/bin/g++-mp;
        ls -l /usr/local/bin/gcc-* /usr/local/bin/g++-*;
     fi'

script:
  - '[[ "$BUILD_MATLAB" == "1" ]] || octave --eval "build_m2c -force"'
  - '[[ "$BUILD_MATLAB" == "0" ]] || ls -l /usr/local/bin/mex && octave --eval "build_m2c -force -matlab"'
