os: linux
dist: trusty
sudo: required
language: C

env:
  matrix:
  - UPDATE_REPOSITORY="true"
  - UPDATE_REPOSITORY="add-apt-repository -y ppa:octave/stable"

before_install:
  - sudo $UPDATE_REPOSITORY
  - sudo apt-get update -q
  - sudo apt-get install -y octave bsdtar liboctave-dev mpich2 libmpich2-dev
  - curl -L "$URL" | sudo bsdtar zxf - -C /usr/local --strip-components 2
  - sudo ln -s -f /usr/local/MATLAB/R2016b/bin/matlab /usr/local/bin
  - sudo ln -s -f /usr/local/MATLAB/R2016b/bin/mex /usr/local/bin

script:
  - octave --eval "build_m2c -force"
  - octave --eval "build_m2c -force -matlab"
