os: linux
dist: trusty
sudo: required
language: C

before_install:
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -q
  - sudo apt-get install -y octave bsdtar liboctave-dev

script:
  - octave --eval "build_m2c -force"
