language: C

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: UPDATE_REPOSITORY="true"
    - os: linux
      dist: trusty
      sudo: required
      env: UPDATE_REPOSITORY="add-apt-repository -y ppa:octave/stable"
    - os: osx
      env: MATLAB=0
    - os: osx
      env: MATLAB=1

before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo $UPDATE_REPOSITORY;
        sudo apt-get update -q;
        sudo apt-get install -y octave bsdtar liboctave-dev mpich2 libmpich2-dev;
        curl -L "$URL" | sudo bsdtar zxf - -C /usr/local --strip-components 2;
        sudo ln -s -f /usr/local/MATLAB/R*/bin/mex /usr/local/bin;
      fi'
  # For Mac, install Octave and link g++-7 to g++-mp
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew tap homebrew/science;
        brew update;
        brew install --without-java octave;
        brew install mpich2;
        curl -L "$URL_OSX" | sudo bsdtar zxf - -C /Applications --strip-components 1;
        sudo ln -s -f /Applications/MATLAB_R*/bin/mex /usr/local/bin;
        ln -s -f /usr/local/bin/gcc-7 /usr/local/bin/gcc-mp;
        ln -s -f /usr/local/bin/g++-7 /usr/local/bin/g++-mp;
        ls -l /usr/local/bin/gcc-* /usr/local/bin/g++-*;
     fi'

script:
  - '[[ "$MATLAB" == "1" ]] || octave --eval "build_m2c -force"'
  - '[[ "$MATLAB" == "0" ]] || ls -l /usr/local/bin/mex && octave --eval "build_m2c -force -matlab"'
